### ISSUE TITLE
Current PKGBUILD forces usage of `python-pytorch-rocm` instead of allowing `opt`-variant

### ISSUE THREAD

**Issue by Sir-Photch** [rocm-arch/python-torchvision-rocm#17]
I am experiencing this issue where running
```console
$ paru -Syu python-pytorch-opt-rocm python-torchvision-rocm
```
yields:
```
warning: removing 'python-pytorch-rocm' from target list because it conflicts with 'python-pytorch-opt-rocm'
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'python-pytorch-rocm>=2.1.0' required by python-torchvision-rocm
```
Why does this package have a hard requirement on `python-pytorch-rocm`?

I am myself not quite sure why there is this issue, currently, [`python-pytorch-opt-rocm`](https://archlinux.org/packages/extra/x86_64/python-pytorch-opt-rocm/) provides `python-pytorch-rocm` anyway so this shouldn't be an issue, right?

**Comment by wuxxin** [comment]
i didn't know, but apparently "depends" does compare with names in "provides" if a version is specified but "provides" does not specify a version. i changed it to depend without version, and conflict (with a version)

**Comment by Sir-Photch** [comment]
Seems to be fixed. Thanks!
