### ISSUE TITLE
Consider implementing pytorch/vision#8096

### ISSUE THREAD

**Issue by tiziodcaio** [rocm-arch/python-torchvision-rocm#18]
Consider implementing pytorch/vision#8096 to resolve ffmpeg4.4 hard-dep

**Comment by wuxxin** [comment]
ty, i'll try to be in sync with [python-pytorch](https://gitlab.archlinux.org/archlinux/packaging/packages/python-pytorch/-/blob/main/PKGBUILD?ref_type=heads) on arch which currently also depends on ffmpeg4.4

**Comment by wuxxin** [comment]
implemented in https://github.com/rocm-arch/python-torchvision-rocm/commit/c3bb646d81365620587d7401f3f80d102c7c03ec , thank you for the patch
