### ISSUE TITLE
Set ROCm arch for CPU-only machine

### ISSUE THREAD

**Issue by petronny** [rocm-arch/python-torchvision-rocm#4]
Hi, thanks for update to 0.14.1 but now I need to set ROCm arch(s) for CPU-only machine to build this package.

Could you include a commented line like
```shell
#ROCM_ARCH=gfx906,gfx1030,gfx908,gfx90a
```
in the PKGBUILD for CPU-only machine?

Build log:
```
-- Caffe2: Protobuf version 3.21.12.0
CMake Error at /usr/lib/cmake/Caffe2/public/utils.cmake:370 (message):
   Could not detect ROCm arch for GPUs on machine. Result: 'No such file or directory'
Call Stack (most recent call first):
  /usr/lib/cmake/Caffe2/public/LoadHIP.cmake:137 (torch_hip_get_arch_list)
  /usr/lib/cmake/Caffe2/Caffe2Config.cmake:82 (include)
  /usr/lib/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:23 (find_package)


-- Configuring incomplete, errors occurred!
See also "/build/python-torchvision-rocm/src/vision-0.14.1/build/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
```
https://github.com/arch4edu/cactus/actions/runs/4194818751/jobs/7273485948

**Comment by wuxxin** [comment]
hi, ty for maintaining arch4edu, to accommodate your needs, 
i changed the build to populate PYTORCH_ROCM_ARCH if not set with defaults taken from arch:community:python-pytorch-rocm@1.13.1 which equals to:
`PYTORCH_ROCM_ARCH="gfx900;gfx906;gfx908;gfx90a;gfx1030"`
i think that should work for the build case without rocm hardware as expected.

**Comment by petronny** [comment]
Thanks! Successfully build. But the size 

https://github.com/arch4edu/arch4edu/commit/0f7e129fbe829cc5021d6857a07bdc0256080cb3

https://github.com/arch4edu/cactus/actions/runs/4209090164
